# Generated by Django 3.0.2 on 2020-01-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('short_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('public_date', models.DateTimeField(auto_now=True)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
    ]
